language: node_js
node_js:
- stable
env:
  global:
    secure: Nb4WSez7R68X6GkAIkJ0Rmm3zAnm2fkKhFStJhUw+0DpAwojQPHfegjwOy+S1RGxk7AQQrU6SlH8mpJKuPvMcR6y0Pm9koOgEQNMRyir35FiCxjRzFe/m2QXev4X5D4YWzU+0HU8qO17giCI2FzMDGi9rdnIUOfIF5qpHJYMay+k9m1qboqOGsb16dWMcv6xwcgSlGD49/GQ+z5Rk8JZsUiWuC8ICwUSkLbaaNkUEFItNf5FnL2RBXBGpN/wDRkrgiY77f52j8haxbitEatfgd3N0AHX2Etg/tA8CLUdLxLuQRH7KOqJYywmE8I6rXfQWCEs9JBTcyLVZbH6zX6yjmKqsDGhq00aSiRZrWpRdhjMD3C7YX8KoHh8I1R945ZgGg9di+v+tDMcwNq8EUZP61X4itoEsg4SqFdSgGuhpjbPi5GjtjQgAypc+1bK5TH5MpnqlzxiewSKDVYSINZi7iIlvxFWyoJm4q7jMNjpL0WGFFOWHWmWAON2mC+S3s7WMWmHp4Z5XJKTG9K2PVlC8jhuRsWLnHk5R4FWIouojKpnR+yyIPSiI6gDpwxQ4C89GXMnuVUVez+x96DiqTyDKLrFUJoYsdbVmKsiv8meQ42UAKf9/OYUAVfjFWFhKNP7s0auQcYrzJeaZ92xQ2qBA8ToNxaLftxUS06dvMYl4aM=
